"""Out-of-sample weekly backtest for the AI signal portfolio."""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path
from typing import Any, Dict, List, Mapping

import numpy as np
import pandas as pd

from model_train import (
    align_to_business_days,
    build_business_days,
    build_tradability_mask,
    build_universe,
    json_default,
    load_config,
    prepare_wide_panel,
)
from optimizer import (
    compute_turnover,
    convert_zscores_to_expected_returns,
    ensure_positive_semidefinite,
    estimate_covariance,
    optimize_long_only_mean_variance,
)


LOGGER = logging.getLogger(__name__)


def setup_logging(output_dir: Path) -> None:
    """Configure console and file logging for the backtest."""
    output_dir.mkdir(parents=True, exist_ok=True)
    log_path = output_dir / "backtest.log"
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(message)s",
        handlers=[logging.StreamHandler(), logging.FileHandler(log_path, encoding="utf-8")],
        force=True,
    )


def load_market_data(config: Mapping[str, Any]) -> Dict[str, Any]:
    """Load only the sheets needed for benchmarking and realized returns."""
    workbook_path = Path(config["paths"]["workbook_path"])
    data_cfg = config["data"]
    market_cap_sheet = data_cfg.get("market_cap_sheet", "CUR_MKT_CAP")
    sheets = pd.read_excel(
        workbook_path,
        sheet_name=[
            data_cfg["universe_sheet"],
            data_cfg["business_days_sheet"],
            data_cfg["price_sheet"],
            market_cap_sheet,
        ],
        engine="openpyxl",
    )

    universe = build_universe(sheets[data_cfg["universe_sheet"]])
    business_days = build_business_days(sheets[data_cfg["business_days_sheet"]])
    assets = universe["short_ticker"].tolist()

    prices = align_to_business_days(
        prepare_wide_panel(sheets[data_cfg["price_sheet"]], assets),
        business_days,
    )
    market_caps = align_to_business_days(
        prepare_wide_panel(sheets[market_cap_sheet], assets),
        business_days,
    )
    tradability_mask, start_dates = build_tradability_mask(prices, business_days, config)
    daily_returns = prices.pct_change()

    return {
        "universe": universe,
        "business_days": business_days,
        "prices": prices,
        "market_caps": market_caps,
        "tradability_mask": tradability_mask,
        "daily_returns": daily_returns,
        "tradability_start_dates": start_dates,
    }


def load_alpha_predictions(config: Mapping[str, Any]) -> pd.DataFrame:
    """Load OOS alpha predictions generated by the model stage."""
    alpha_path = Path(config["paths"]["results_dir"]) / "alpha_predictions.csv"
    if not alpha_path.exists():
        raise FileNotFoundError(f"Alpha predictions not found: {alpha_path}")
    predictions = pd.read_csv(alpha_path, parse_dates=["date"])
    predictions = predictions.sort_values(["date", "asset"]).reset_index(drop=True)
    return predictions


def next_business_day(current_date: pd.Timestamp, business_days: pd.DatetimeIndex) -> pd.Timestamp | None:
    """Return the next business day after the provided date."""
    idx = business_days.searchsorted(pd.Timestamp(current_date), side="right")
    if idx >= len(business_days):
        return None
    return pd.Timestamp(business_days[idx])


def build_expected_return_scale_map(
    alpha_predictions: pd.DataFrame,
    rebalance_dates: pd.DatetimeIndex,
    config: Mapping[str, Any],
) -> Dict[pd.Timestamp, float]:
    """Calibrate z-score scale using only matured historical realized targets."""
    exp_cfg = config["backtest"]["expected_return"]
    lookback = int(exp_cfg["scale_lookback_rebalances"])
    maturity_gap = int(exp_cfg["label_maturity_rebalances"])
    default_scale = float(exp_cfg["default_scale"])
    min_scale = float(exp_cfg["min_scale"])
    max_scale = float(exp_cfg["max_scale"])
    method = str(exp_cfg.get("scale_method", "regression_beta"))

    scored = alpha_predictions.loc[:, ["date", "alpha_zscore", "target_specific_return"]].dropna().copy()
    def per_date_scale(frame: pd.DataFrame) -> float:
        z = frame["alpha_zscore"].to_numpy(dtype=float)
        y = frame["target_specific_return"].to_numpy(dtype=float)
        denom = float(np.dot(z, z))
        if denom <= 1.0e-12:
            return float("nan")
        return float(np.dot(z, y) / denom)

    regression_scale = scored.groupby("date").apply(per_date_scale).sort_index()
    realized_dispersion = scored.groupby("date")["target_specific_return"].std(ddof=0).sort_index()

    scale_map: Dict[pd.Timestamp, float] = {}
    for idx, rebalance_date in enumerate(rebalance_dates):
        matured_dates = rebalance_dates[: max(0, idx - maturity_gap)]
        if method == "regression_beta":
            history = regression_scale.reindex(matured_dates).dropna().tail(lookback)
        else:
            history = pd.Series(dtype=float)
        if history.empty:
            history = realized_dispersion.reindex(matured_dates).dropna().tail(lookback)
        scale = float(history.median()) if not history.empty else default_scale
        scale_map[pd.Timestamp(rebalance_date)] = float(np.clip(scale, min_scale, max_scale))
    return scale_map


def build_benchmark_weights(
    rebalance_date: pd.Timestamp,
    assets: List[str],
    market_caps: pd.DataFrame,
    tradability_mask: pd.DataFrame,
) -> pd.Series:
    """Construct a market-cap-weighted benchmark over the tradable universe."""
    caps = market_caps.loc[rebalance_date, assets].copy()
    tradable = tradability_mask.loc[rebalance_date, assets].fillna(False)
    caps = caps.where(tradable & caps.notna() & (caps > 0.0), 0.0)
    if float(caps.sum()) <= 0:
        weights = pd.Series(1.0 / len(assets), index=assets)
    else:
        weights = caps / float(caps.sum())
    return weights.astype(float)


def compute_period_asset_returns(
    prices: pd.DataFrame,
    start_date: pd.Timestamp,
    end_date: pd.Timestamp,
    assets: List[str],
) -> pd.Series:
    """Compute close-to-close holding-period returns."""
    start_prices = prices.loc[start_date, assets]
    end_prices = prices.loc[end_date, assets]
    returns = end_prices.divide(start_prices) - 1.0
    return returns.replace([np.inf, -np.inf], np.nan).fillna(0.0)


def compute_summary_metrics(period_returns: pd.DataFrame) -> Dict[str, float]:
    """Compute headline backtest metrics from weekly returns."""
    weekly_periods = max(len(period_returns), 1)
    portfolio = period_returns["portfolio_net_return"].fillna(0.0)
    benchmark = period_returns["benchmark_return"].fillna(0.0)
    excess = portfolio - benchmark

    portfolio_curve = (1.0 + portfolio).cumprod()
    benchmark_curve = (1.0 + benchmark).cumprod()
    running_max = portfolio_curve.cummax()
    drawdown = portfolio_curve.divide(running_max) - 1.0

    annual_return = float(portfolio.mean() * 52.0)
    annual_vol = float(portfolio.std(ddof=0) * np.sqrt(52.0))
    benchmark_return = float(benchmark.mean() * 52.0)
    benchmark_vol = float(benchmark.std(ddof=0) * np.sqrt(52.0))
    excess_return = float(excess.mean() * 52.0)
    tracking_error = float(excess.std(ddof=0) * np.sqrt(52.0))

    return {
        "weeks": int(weekly_periods),
        "total_return": float(portfolio_curve.iloc[-1] - 1.0),
        "annualized_return": annual_return,
        "annualized_volatility": annual_vol,
        "sharpe_ratio": float(annual_return / annual_vol) if annual_vol > 0 else float("nan"),
        "max_drawdown": float(drawdown.min()),
        "benchmark_total_return": float(benchmark_curve.iloc[-1] - 1.0),
        "benchmark_annualized_return": benchmark_return,
        "benchmark_annualized_volatility": benchmark_vol,
        "excess_annualized_return": excess_return,
        "tracking_error": tracking_error,
        "information_ratio": float(excess_return / tracking_error) if tracking_error > 0 else float("nan"),
        "average_turnover": float(period_returns["turnover"].mean()),
        "total_transaction_cost": float(period_returns["transaction_cost"].sum()),
        "hit_rate_vs_benchmark": float((excess > 0).mean()),
    }


def run_backtest(config: Mapping[str, Any]) -> Dict[str, Any]:
    """Run the OOS weekly portfolio construction and backtest."""
    output_dir = Path(config["paths"]["backtest_dir"])
    setup_logging(output_dir)
    LOGGER.info("Loading market data and OOS alpha predictions.")

    market_data = load_market_data(config)
    alpha_predictions = load_alpha_predictions(config)
    universe = market_data["universe"]
    prices = market_data["prices"]
    market_caps = market_data["market_caps"]
    daily_returns = market_data["daily_returns"]
    tradability_mask = market_data["tradability_mask"]
    business_days = market_data["business_days"]

    rebalance_dates = pd.DatetimeIndex(sorted(alpha_predictions["date"].unique()))
    scale_map = build_expected_return_scale_map(alpha_predictions, rebalance_dates, config)
    sector_map = universe.set_index("short_ticker")["Sector"]
    cost_rate = float(config["backtest"]["transaction_cost_bps"]) / 10000.0
    lookback = int(config["backtest"]["covariance"]["lookback_bdays"])
    fallback_shrinkage = float(config["backtest"]["covariance"]["fallback_shrinkage"])

    weight_rows: List[Dict[str, Any]] = []
    benchmark_weight_rows: List[Dict[str, Any]] = []
    return_rows: List[Dict[str, Any]] = []
    diagnostic_rows: List[Dict[str, Any]] = []
    previous_portfolio_weights = pd.Series(0.0, index=universe["short_ticker"].tolist())
    fallback_counts = {"base": 0, "fallback_shrinkage": 0, "diagonal": 0, "heuristic": 0}

    for idx, rebalance_date in enumerate(rebalance_dates[:-1]):
        next_rebalance_date = pd.Timestamp(rebalance_dates[idx + 1])
        execution_date = next_business_day(pd.Timestamp(rebalance_date), business_days)
        next_execution_date = next_business_day(next_rebalance_date, business_days)
        if execution_date is None or next_execution_date is None:
            continue

        alpha_slice = alpha_predictions.loc[alpha_predictions["date"] == rebalance_date].copy()
        if alpha_slice.empty:
            continue

        assets = alpha_slice["asset"].tolist()
        benchmark_weights = build_benchmark_weights(
            rebalance_date=pd.Timestamp(rebalance_date),
            assets=assets,
            market_caps=market_caps,
            tradability_mask=tradability_mask,
        )
        scale = scale_map[pd.Timestamp(rebalance_date)]
        alpha_slice["expected_return_20d"] = convert_zscores_to_expected_returns(
            alpha_slice.set_index("asset")["alpha_zscore"],
            scale=scale,
            config=config,
        ).reindex(alpha_slice["asset"]).to_numpy()
        expected_returns = alpha_slice.set_index("asset")["expected_return_20d"]

        returns_window = daily_returns.loc[: pd.Timestamp(rebalance_date), assets].tail(lookback)
        covariance, cov_diag = estimate_covariance(returns_window, assets, config)
        optimization = optimize_long_only_mean_variance(
            expected_returns=expected_returns,
            covariance=covariance,
            benchmark_weights=benchmark_weights,
            current_weights=previous_portfolio_weights.reindex(assets).fillna(0.0),
            sectors=sector_map.reindex(assets),
            config=config,
        )
        optimization["diagnostics"].update({"covariance_mode": cov_diag["mode"], "covariance_shrinkage": cov_diag["shrinkage"]})
        fallback_counts["base"] += int(optimization["diagnostics"]["success"])

        if not optimization["diagnostics"]["success"]:
            covariance, cov_diag = estimate_covariance(returns_window, assets, config, shrinkage=fallback_shrinkage)
            retry = optimize_long_only_mean_variance(
                expected_returns=expected_returns,
                covariance=covariance,
                benchmark_weights=benchmark_weights,
                current_weights=previous_portfolio_weights.reindex(assets).fillna(0.0),
                sectors=sector_map.reindex(assets),
                config=config,
            )
            retry["diagnostics"].update({"covariance_mode": cov_diag["mode"], "covariance_shrinkage": cov_diag["shrinkage"]})
            if retry["diagnostics"]["success"]:
                optimization = retry
                fallback_counts["fallback_shrinkage"] += 1
            else:
                diagonal_cov = pd.DataFrame(
                    np.diag(np.diag(covariance.reindex(index=assets, columns=assets).to_numpy(dtype=float))),
                    index=assets,
                    columns=assets,
                )
                diagonal_cov = ensure_positive_semidefinite(
                    diagonal_cov,
                    floor=float(config["backtest"]["covariance"]["diagonal_floor"]),
                )
                diagonal_try = optimize_long_only_mean_variance(
                    expected_returns=expected_returns,
                    covariance=diagonal_cov,
                    benchmark_weights=benchmark_weights,
                    current_weights=previous_portfolio_weights.reindex(assets).fillna(0.0),
                    sectors=sector_map.reindex(assets),
                    config=config,
                )
                diagonal_try["diagnostics"].update({"covariance_mode": "diagonal_only", "covariance_shrinkage": 1.0})
                if diagonal_try["diagnostics"]["success"]:
                    optimization = diagonal_try
                    fallback_counts["diagonal"] += 1
                else:
                    optimization = diagonal_try
                    fallback_counts["heuristic"] += 1

        portfolio_weights = optimization["weights"].reindex(universe["short_ticker"].tolist()).fillna(0.0)
        benchmark_full = benchmark_weights.reindex(universe["short_ticker"].tolist()).fillna(0.0)
        turnover = compute_turnover(portfolio_weights, previous_portfolio_weights)
        transaction_cost = turnover * cost_rate

        period_asset_returns = compute_period_asset_returns(
            prices=prices,
            start_date=execution_date,
            end_date=next_execution_date,
            assets=universe["short_ticker"].tolist(),
        )
        portfolio_gross_return = float(portfolio_weights.dot(period_asset_returns))
        benchmark_return = float(benchmark_full.dot(period_asset_returns))
        portfolio_net_return = portfolio_gross_return - transaction_cost

        return_rows.append(
            {
                "rebalance_date": pd.Timestamp(rebalance_date),
                "execution_date": execution_date,
                "next_rebalance_date": next_rebalance_date,
                "next_execution_date": next_execution_date,
                "portfolio_gross_return": portfolio_gross_return,
                "portfolio_net_return": portfolio_net_return,
                "benchmark_return": benchmark_return,
                "active_return": portfolio_net_return - benchmark_return,
                "turnover": turnover,
                "transaction_cost": transaction_cost,
                "expected_return_scale": scale,
                "holdings": int((portfolio_weights > 0).sum()),
                "optimizer_success": bool(optimization["diagnostics"]["success"]),
                "optimizer_mode": optimization["diagnostics"]["mode"],
                "covariance_mode": optimization["diagnostics"]["covariance_mode"],
                "covariance_shrinkage": optimization["diagnostics"]["covariance_shrinkage"],
            }
        )

        alpha_by_asset = alpha_slice.set_index("asset")
        for asset in universe["short_ticker"].tolist():
            weight_rows.append(
                {
                    "rebalance_date": pd.Timestamp(rebalance_date),
                    "execution_date": execution_date,
                    "asset": asset,
                    "asset_name": universe.set_index("short_ticker").loc[asset, "Name"],
                    "sector": universe.set_index("short_ticker").loc[asset, "Sector"],
                    "portfolio_weight": float(portfolio_weights.get(asset, 0.0)),
                    "raw_prediction": float(alpha_by_asset.loc[asset, "raw_prediction"]) if asset in alpha_by_asset.index else np.nan,
                    "alpha_zscore": float(alpha_by_asset.loc[asset, "alpha_zscore"]) if asset in alpha_by_asset.index else np.nan,
                    "expected_return_20d": float(alpha_by_asset.loc[asset, "expected_return_20d"]) if asset in alpha_by_asset.index else np.nan,
                }
            )
            benchmark_weight_rows.append(
                {
                    "rebalance_date": pd.Timestamp(rebalance_date),
                    "execution_date": execution_date,
                    "asset": asset,
                    "asset_name": universe.set_index("short_ticker").loc[asset, "Name"],
                    "sector": universe.set_index("short_ticker").loc[asset, "Sector"],
                    "benchmark_weight": float(benchmark_full.get(asset, 0.0)),
                }
            )

        diagnostics = dict(optimization["diagnostics"])
        diagnostics.update(
            {
                "rebalance_date": pd.Timestamp(rebalance_date),
                "execution_date": execution_date,
                "next_execution_date": next_execution_date,
                "turnover_realized": turnover,
                "transaction_cost": transaction_cost,
                "expected_return_scale": scale,
            }
        )
        diagnostic_rows.append(diagnostics)
        previous_portfolio_weights = portfolio_weights

    period_returns = pd.DataFrame(return_rows).sort_values("rebalance_date")
    summary = compute_summary_metrics(period_returns)
    summary["fallback_counts"] = fallback_counts
    summary["tradability_start_dates"] = market_data["tradability_start_dates"]

    pd.DataFrame(weight_rows).to_csv(output_dir / "portfolio_weights.csv", index=False)
    pd.DataFrame(benchmark_weight_rows).to_csv(output_dir / "benchmark_weights.csv", index=False)
    period_returns.to_csv(output_dir / "backtest_returns.csv", index=False)
    pd.DataFrame(diagnostic_rows).to_csv(output_dir / "optimizer_diagnostics.csv", index=False)
    with (output_dir / "backtest_summary.json").open("w", encoding="utf-8") as handle:
        json.dump(summary, handle, indent=2, ensure_ascii=False, default=json_default)
    with (output_dir / "backtest_diagnostics.json").open("w", encoding="utf-8") as handle:
        json.dump({"rows": diagnostic_rows}, handle, indent=2, ensure_ascii=False, default=json_default)

    LOGGER.info("Saved portfolio weights to %s", output_dir / "portfolio_weights.csv")
    LOGGER.info("Saved backtest returns to %s", output_dir / "backtest_returns.csv")
    return {
        "backtest_dir": str(output_dir),
        "summary_path": str(output_dir / "backtest_summary.json"),
        "returns_path": str(output_dir / "backtest_returns.csv"),
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run the OOS weekly portfolio backtest.")
    parser.add_argument("--config", default="config.yaml", help="Path to the YAML config file.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    config = load_config(args.config)
    run_backtest(config)


if __name__ == "__main__":
    main()

